/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ExerciseIndexRouteImport } from './routes/exercise.index'
import { Route as ExerciseLibraryRouteImport } from './routes/exercise.library'
import { Route as ExerciseMyEquipmentRouteImport } from './routes/exercise.my-equipment'
import { Route as ExploreLibraryRouteImport } from './routes/explore.library'
import { Route as ExploreMyEquipmentRouteImport } from './routes/explore.my-equipment'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password_.reset'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password_.verify'
import { Route as LabTestReportProductNameRouteImport } from './routes/lab-test-report.$productName'
import { Route as OrdersDetailsRouteImport } from './routes/orders.details'
import { Route as OrdersSuccessRouteImport } from './routes/orders.success'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as ProfileChangePasswordRouteImport } from './routes/profile.change-password'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileReferralRouteImport } from './routes/profile.referral'
import { Route as ProfileWishlistRouteImport } from './routes/profile.wishlist'
import { Route as WalletAddRouteImport } from './routes/wallet.add'
import { Route as ExerciseActiveIdRouteImport } from './routes/exercise.active.$id'
import { Route as ExerciseEquipmentIdRouteImport } from './routes/exercise.equipment.$id'
import { Route as ExploreActiveIdRouteImport } from './routes/explore.active.$id'
import { Route as ExploreEquipmentIdRouteImport } from './routes/explore.equipment.$id'
import { Route as ApiPaymentsZiinaCreateRouteImport } from './routes/api/payments/ziina/create'
import { Route as ApiPaymentsZiinaVerifyRouteImport } from './routes/api/payments/ziina/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ExerciseIndexRoute = ExerciseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExerciseLibraryRoute = ExerciseLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExerciseMyEquipmentRoute = ExerciseMyEquipmentRouteImport.update({
  id: '/my-equipment',
  path: '/my-equipment',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExploreLibraryRoute = ExploreLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreMyEquipmentRoute = ExploreMyEquipmentRouteImport.update({
  id: '/my-equipment',
  path: '/my-equipment',
  getParentRoute: () => ExploreRoute,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/forgot-password_/reset',
  path: '/forgot-password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/forgot-password_/verify',
  path: '/forgot-password/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestReportProductNameRoute =
  LabTestReportProductNameRouteImport.update({
    id: '/lab-test-report/$productName',
    path: '/lab-test-report/$productName',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrdersDetailsRoute = OrdersDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersSuccessRoute = OrdersSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OrdersRoute,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileChangePasswordRoute = ProfileChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileReferralRoute = ProfileReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileWishlistRoute = ProfileWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ProfileRoute,
} as any)
const WalletAddRoute = WalletAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => WalletRoute,
} as any)
const ExerciseActiveIdRoute = ExerciseActiveIdRouteImport.update({
  id: '/active/$id',
  path: '/active/$id',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExerciseEquipmentIdRoute = ExerciseEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExploreActiveIdRoute = ExploreActiveIdRouteImport.update({
  id: '/active/$id',
  path: '/active/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreEquipmentIdRoute = ExploreEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ApiPaymentsZiinaCreateRoute = ApiPaymentsZiinaCreateRouteImport.update({
  id: '/api/payments/ziina/create',
  path: '/api/payments/ziina/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsZiinaVerifyRoute = ApiPaymentsZiinaVerifyRouteImport.update({
  id: '/api/payments/ziina/verify',
  path: '/api/payments/ziina/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exercise': typeof ExerciseRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/exercise/library': typeof ExerciseLibraryRoute
  '/exercise/my-equipment': typeof ExerciseMyEquipmentRoute
  '/explore/library': typeof ExploreLibraryRoute
  '/explore/my-equipment': typeof ExploreMyEquipmentRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/lab-test-report/$productName': typeof LabTestReportProductNameRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/orders/success': typeof OrdersSuccessRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/wallet/add': typeof WalletAddRoute
  '/blog/': typeof BlogIndexRoute
  '/exercise/': typeof ExerciseIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/exercise/active/$id': typeof ExerciseActiveIdRoute
  '/exercise/equipment/$id': typeof ExerciseEquipmentIdRoute
  '/explore/active/$id': typeof ExploreActiveIdRoute
  '/explore/equipment/$id': typeof ExploreEquipmentIdRoute
  '/api/payments/ziina/create': typeof ApiPaymentsZiinaCreateRoute
  '/api/payments/ziina/verify': typeof ApiPaymentsZiinaVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/exercise/library': typeof ExerciseLibraryRoute
  '/exercise/my-equipment': typeof ExerciseMyEquipmentRoute
  '/explore/library': typeof ExploreLibraryRoute
  '/explore/my-equipment': typeof ExploreMyEquipmentRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/lab-test-report/$productName': typeof LabTestReportProductNameRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/orders/success': typeof OrdersSuccessRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/wallet/add': typeof WalletAddRoute
  '/blog': typeof BlogIndexRoute
  '/exercise': typeof ExerciseIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/exercise/active/$id': typeof ExerciseActiveIdRoute
  '/exercise/equipment/$id': typeof ExerciseEquipmentIdRoute
  '/explore/active/$id': typeof ExploreActiveIdRoute
  '/explore/equipment/$id': typeof ExploreEquipmentIdRoute
  '/api/payments/ziina/create': typeof ApiPaymentsZiinaCreateRoute
  '/api/payments/ziina/verify': typeof ApiPaymentsZiinaVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exercise': typeof ExerciseRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/exercise/library': typeof ExerciseLibraryRoute
  '/exercise/my-equipment': typeof ExerciseMyEquipmentRoute
  '/explore/library': typeof ExploreLibraryRoute
  '/explore/my-equipment': typeof ExploreMyEquipmentRoute
  '/forgot-password_/reset': typeof ForgotPasswordResetRoute
  '/forgot-password_/verify': typeof ForgotPasswordVerifyRoute
  '/lab-test-report/$productName': typeof LabTestReportProductNameRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/orders/success': typeof OrdersSuccessRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/wallet/add': typeof WalletAddRoute
  '/blog/': typeof BlogIndexRoute
  '/exercise/': typeof ExerciseIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/exercise/active/$id': typeof ExerciseActiveIdRoute
  '/exercise/equipment/$id': typeof ExerciseEquipmentIdRoute
  '/explore/active/$id': typeof ExploreActiveIdRoute
  '/explore/equipment/$id': typeof ExploreEquipmentIdRoute
  '/api/payments/ziina/create': typeof ApiPaymentsZiinaCreateRoute
  '/api/payments/ziina/verify': typeof ApiPaymentsZiinaVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/exercise'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/profile'
    | '/search'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/blog/$slug'
    | '/exercise/library'
    | '/exercise/my-equipment'
    | '/explore/library'
    | '/explore/my-equipment'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/lab-test-report/$productName'
    | '/orders/details'
    | '/orders/success'
    | '/policies/$slug'
    | '/product/$slug'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/referral'
    | '/profile/wishlist'
    | '/wallet/add'
    | '/blog/'
    | '/exercise/'
    | '/profile/'
    | '/exercise/active/$id'
    | '/exercise/equipment/$id'
    | '/explore/active/$id'
    | '/explore/equipment/$id'
    | '/api/payments/ziina/create'
    | '/api/payments/ziina/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/search'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/blog/$slug'
    | '/exercise/library'
    | '/exercise/my-equipment'
    | '/explore/library'
    | '/explore/my-equipment'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/lab-test-report/$productName'
    | '/orders/details'
    | '/orders/success'
    | '/policies/$slug'
    | '/product/$slug'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/referral'
    | '/profile/wishlist'
    | '/wallet/add'
    | '/blog'
    | '/exercise'
    | '/profile'
    | '/exercise/active/$id'
    | '/exercise/equipment/$id'
    | '/explore/active/$id'
    | '/explore/equipment/$id'
    | '/api/payments/ziina/create'
    | '/api/payments/ziina/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/exercise'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/profile'
    | '/search'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/blog/$slug'
    | '/exercise/library'
    | '/exercise/my-equipment'
    | '/explore/library'
    | '/explore/my-equipment'
    | '/forgot-password_/reset'
    | '/forgot-password_/verify'
    | '/lab-test-report/$productName'
    | '/orders/details'
    | '/orders/success'
    | '/policies/$slug'
    | '/product/$slug'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/referral'
    | '/profile/wishlist'
    | '/wallet/add'
    | '/blog/'
    | '/exercise/'
    | '/profile/'
    | '/exercise/active/$id'
    | '/exercise/equipment/$id'
    | '/explore/active/$id'
    | '/explore/equipment/$id'
    | '/api/payments/ziina/create'
    | '/api/payments/ziina/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ExerciseRoute: typeof ExerciseRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRouteWithChildren
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
  LabTestReportProductNameRoute: typeof LabTestReportProductNameRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPaymentsZiinaCreateRoute: typeof ApiPaymentsZiinaCreateRoute
  ApiPaymentsZiinaVerifyRoute: typeof ApiPaymentsZiinaVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/exercise/': {
      id: '/exercise/'
      path: '/'
      fullPath: '/exercise/'
      preLoaderRoute: typeof ExerciseIndexRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/exercise/library': {
      id: '/exercise/library'
      path: '/library'
      fullPath: '/exercise/library'
      preLoaderRoute: typeof ExerciseLibraryRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/exercise/my-equipment': {
      id: '/exercise/my-equipment'
      path: '/my-equipment'
      fullPath: '/exercise/my-equipment'
      preLoaderRoute: typeof ExerciseMyEquipmentRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/explore/library': {
      id: '/explore/library'
      path: '/library'
      fullPath: '/explore/library'
      preLoaderRoute: typeof ExploreLibraryRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/my-equipment': {
      id: '/explore/my-equipment'
      path: '/my-equipment'
      fullPath: '/explore/my-equipment'
      preLoaderRoute: typeof ExploreMyEquipmentRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/forgot-password_/reset': {
      id: '/forgot-password_/reset'
      path: '/forgot-password/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password_/verify': {
      id: '/forgot-password_/verify'
      path: '/forgot-password/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-test-report/$productName': {
      id: '/lab-test-report/$productName'
      path: '/lab-test-report/$productName'
      fullPath: '/lab-test-report/$productName'
      preLoaderRoute: typeof LabTestReportProductNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/details': {
      id: '/orders/details'
      path: '/details'
      fullPath: '/orders/details'
      preLoaderRoute: typeof OrdersDetailsRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/success': {
      id: '/orders/success'
      path: '/success'
      fullPath: '/orders/success'
      preLoaderRoute: typeof OrdersSuccessRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/change-password': {
      id: '/profile/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof ProfileChangePasswordRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/referral': {
      id: '/profile/referral'
      path: '/referral'
      fullPath: '/profile/referral'
      preLoaderRoute: typeof ProfileReferralRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/wishlist': {
      id: '/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof ProfileWishlistRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/wallet/add': {
      id: '/wallet/add'
      path: '/add'
      fullPath: '/wallet/add'
      preLoaderRoute: typeof WalletAddRouteImport
      parentRoute: typeof WalletRoute
    }
    '/exercise/active/$id': {
      id: '/exercise/active/$id'
      path: '/active/$id'
      fullPath: '/exercise/active/$id'
      preLoaderRoute: typeof ExerciseActiveIdRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/exercise/equipment/$id': {
      id: '/exercise/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/exercise/equipment/$id'
      preLoaderRoute: typeof ExerciseEquipmentIdRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/explore/active/$id': {
      id: '/explore/active/$id'
      path: '/active/$id'
      fullPath: '/explore/active/$id'
      preLoaderRoute: typeof ExploreActiveIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/equipment/$id': {
      id: '/explore/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/explore/equipment/$id'
      preLoaderRoute: typeof ExploreEquipmentIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/api/payments/ziina/create': {
      id: '/api/payments/ziina/create'
      path: '/api/payments/ziina/create'
      fullPath: '/api/payments/ziina/create'
      preLoaderRoute: typeof ApiPaymentsZiinaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/ziina/verify': {
      id: '/api/payments/ziina/verify'
      path: '/api/payments/ziina/verify'
      fullPath: '/api/payments/ziina/verify'
      preLoaderRoute: typeof ApiPaymentsZiinaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExerciseRouteChildren {
  ExerciseLibraryRoute: typeof ExerciseLibraryRoute
  ExerciseMyEquipmentRoute: typeof ExerciseMyEquipmentRoute
  ExerciseIndexRoute: typeof ExerciseIndexRoute
  ExerciseActiveIdRoute: typeof ExerciseActiveIdRoute
  ExerciseEquipmentIdRoute: typeof ExerciseEquipmentIdRoute
}

const ExerciseRouteChildren: ExerciseRouteChildren = {
  ExerciseLibraryRoute: ExerciseLibraryRoute,
  ExerciseMyEquipmentRoute: ExerciseMyEquipmentRoute,
  ExerciseIndexRoute: ExerciseIndexRoute,
  ExerciseActiveIdRoute: ExerciseActiveIdRoute,
  ExerciseEquipmentIdRoute: ExerciseEquipmentIdRoute,
}

const ExerciseRouteWithChildren = ExerciseRoute._addFileChildren(
  ExerciseRouteChildren,
)

interface ExploreRouteChildren {
  ExploreLibraryRoute: typeof ExploreLibraryRoute
  ExploreMyEquipmentRoute: typeof ExploreMyEquipmentRoute
  ExploreActiveIdRoute: typeof ExploreActiveIdRoute
  ExploreEquipmentIdRoute: typeof ExploreEquipmentIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreLibraryRoute: ExploreLibraryRoute,
  ExploreMyEquipmentRoute: ExploreMyEquipmentRoute,
  ExploreActiveIdRoute: ExploreActiveIdRoute,
  ExploreEquipmentIdRoute: ExploreEquipmentIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface OrdersRouteChildren {
  OrdersDetailsRoute: typeof OrdersDetailsRoute
  OrdersSuccessRoute: typeof OrdersSuccessRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersDetailsRoute: OrdersDetailsRoute,
  OrdersSuccessRoute: OrdersSuccessRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProfileRouteChildren {
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileChangePasswordRoute: typeof ProfileChangePasswordRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileReferralRoute: typeof ProfileReferralRoute
  ProfileWishlistRoute: typeof ProfileWishlistRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileChangePasswordRoute: ProfileChangePasswordRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileReferralRoute: ProfileReferralRoute,
  ProfileWishlistRoute: ProfileWishlistRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface WalletRouteChildren {
  WalletAddRoute: typeof WalletAddRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletAddRoute: WalletAddRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ExerciseRoute: ExerciseRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRouteWithChildren,
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
  LabTestReportProductNameRoute: LabTestReportProductNameRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPaymentsZiinaCreateRoute: ApiPaymentsZiinaCreateRoute,
  ApiPaymentsZiinaVerifyRoute: ApiPaymentsZiinaVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
